### PR TITLE
Build unpublished contents and publish them to -dev env

### PR DESCRIPTION
**Pull request by bqbn**
Per https://github.com/mozilla/extension-workshop/issues/191

### CODE REVIEW

**Comment by muffinresearch** [comment]
Hmm looks like the latest run in circle didn't complete.

**Comment by bqbn** [comment]
It didn't start because it is configured to build only "master" and tags. Branches are not built.

I'll merge and fix issues if there are any.

**Comment by bqbn** [comment]
I made a commit so that it builds for all branches, and deploy only for "master" and tags. I think this helps catch errors (if any) when they're still in branches.

**Comment by bqbn** [comment]
Closes https://github.com/mozilla/extension-workshop/issues/191

**Comment by muffinresearch** [comment]
Thanks @bqbn this is working well 👍

**Pull request merged**
