### PR TITLE
Bug #414, Link point to https://addons.mozilla.org

### LINKED ISSUE #414: [Test-permission-requests] Link pointing to addons.mozilla.org is incorrect
### Describe the problem and steps to reproduce it:

1. Open the following documentation page - https://extensionworkshop-dev.allizom.org/documentation/develop/test-permission-requests/#observe-or-verify-install-time-permission-requests
2. Click on  the `addons.mozilla.org` link displayed below:

image

### What happened?
The links is mapped to https://addon.mozilla.org which is invalid ("addon" is missing an 's' at the end)
### What did you expect to happen?
The link should point to https://addons.mozilla.org

### PR DESCRIPTION
**Pull request by virgilt**
Fixes #414

### CODE REVIEW

**Comment by virgilt** [comment]
@championshuttler Thank you for letting me work on it! Don't hesitate to assign me other issues. I want to contribute a lot. Really love Firefox and Mozilla!

**Comment by championshuttler** [comment]
@virgilt Feel free to go to https://codetribute.mozilla.org/

**Comment by caitmuenster** [comment]
Thank you @virgilt! 🎉

We've added your contribution to our [recognition wiki](https://wiki.mozilla.org/Add-ons/Contribute/Recognition) and your Mozillians profile has been vouched. ✨

Welcome onboard! I look forward to seeing you around Mozilla's projects. :)

**Comment by virgilt** [comment]
Wow, this is so awesome! Thank you @caitmuenster

**Pull request merged**
