### PR TITLE
Fixes #503: Fixed padding for landscape mode in mobile browsers

### LINKED ISSUE #503: Landscape with browser chrome makes heading cramped on the homepage
Using an Nexus 7 (Android) running FF Android, when the browser chrome is open it looks like this:

Screen Shot 2019-10-10 at 16 43 12

We should add more space before the heading to allow for this.

### PR DESCRIPTION
**Pull request by majordwarf**
Fixed the crammped header that was being caused on mobile devices when in landscape mode as mentioned here #503 

**How to test:** Fetch the PR locally > Install the dependencies > `yarn start`

### CODE REVIEW

**Comment by muffinresearch** [comment]
@majordwarf Hi, thanks for the patch - however, this is already being worked on by another contributor.

**Comment by majordwarf** [comment]
Oh, I saw the conversation was 4 days old and thought it was a ghosted PR.

**Comment by muffinresearch** [comment]
Before:  


Extension_Workshop___Firefox_Extension_Workshop__Make_the_web_do_what_you_want__If_you_can_dream_it__our_open_souce_API_and_your_HTML__CSS__and_JavaScript_skills_can_make_it_happen_

After:

Screen Shot 2019-10-16 at 12 36 55

**Comment by majordwarf** [comment]
Oh great, I used chromium to test the landscape mode padding. I'll make sure to use multiple browsers to avoid such minor mistakes. Thanks @muffinresearch !

**Comment by caitmuenster** [comment]
Thank you so much for your contribution, @majordwarf! 🎉 We've added it to our [recognition wiki](https://wiki.mozilla.org/Add-ons/Contribute/Recognition). 

Would you be interested in creating an account on mozillians.org? I'd be happy to vouch for you!

**Comment by majordwarf** [comment]
Sorry for the late reply @caitmuenster , was busy with work at University. Made my ID on Mozillians with same username! 😄

**Comment by caitmuenster** [comment]
Thanks, @majordwarf! Your profile has been vouched. 

Welcome onboard! I look forward to seeing you around. :)

**Pull request merged**
