### PR TITLE
Documentation Topics dropdown menu is not closed when user scroll the…

### PR DESCRIPTION
**Pull request by digitigrafo**
… homepage (partial #267)

Contributor: digitigrafo <kiki@digitigrafo.it>

Date: 2020/03/03

### CODE REVIEW

**Comment by caitmuenster** [comment]
@willdurand, with Stuart being out, could you review this on Monday? 

@digitigrafo It looks like our instructions were confusing. :) When you update the content of one of the articles hosted on the site, there are fields on the content pages that note who last updated it and when. No need to list that info for PRs that don't deal with user-facing content. :)

**Comment by digitigrafo** [comment]
> I'm not sure what this patch covers, it looks like a lot of unrelated duplication from the main.scss file.



> I'm not sure what this patch covers, it looks like a lot of unrelated duplication from the main.scss file.

The code that I added is this:
`
.minimize .subfolder {
    display: none;
}
`
probably there was some space ad the begin and git took all the code as changed. I can do another pull request.. @muffinresearch

**Comment by digitigrafo** [comment]
@muffinresearch  you can check this https://github.com/mozilla/extension-workshop/pull/627

**Comment by digitigrafo** [comment]
> @muffinresearch you can check this #627

hem, sorry this is update with the master repo:
 https://github.com/mozilla/extension-workshop/pull/628

**Comment by muffinresearch** [comment]
Closing this as it has been superceded by #628

**Pull request closed without merging**
