### PR TITLE
docs: fix titles

### PR DESCRIPTION
**Pull request by noraj**
unwanted HTML section tags were breaking the markdown parsing

image

### CODE REVIEW

**Comment by muffinresearch** [comment]
As horrible as these sections are, I think the ids are needed (unless it's clear they're not linked to) until this can be properly refactored so that ids are correctly auto-generated and hacks like this are no longer required. As a quick fix, adding a blank line of space under the HTML should fix the rendering. 

A div would almost certainly be a better choice for this rather than having meaningless empty sections, but at some point this whole thing needs replacing so that this kind of thing is no longer needed. See also: #659 #673

**Comment by noraj** [comment]
@muffinresearch Yeah using markdown-it would be what I recommend too (#673). Yeah I could update this PR to add a blank line but is it even wort it? Maybe I'll close this PR in favor for #673 .

**Comment by muffinresearch** [comment]
Adding newlines would at least un-break this page until #673 can be fixed, which is going to be a way off since it's not just as simple as adding the plugin (mainly because the toc is used on the sidebar, so that will make it more complicated)

**Comment by muffinresearch** [comment]
@noraj thanks!

**Comment by caitmuenster** [comment]
Thanks so much, @noraj! 🙌 We've added your contribution to our [recognition wiki](https://wiki.mozilla.org/Add-ons/Contribute/Recognition).

**Pull request merged**
