### PR TITLE
browser_specific_settings to applications

### PR DESCRIPTION
**Pull request by rebloor**
Change as per [Bug 1739640](https://bugzilla.mozilla.org/show_bug.cgi?id=1739640) – the update manifest file does not support `browser_specific_settings`,  rather the code expects `applications`.

### CODE REVIEW

**Comment by rebloor** [comment]
@muffinresearch I understand you can help with review and merge. Thanks.

**Comment by muffinresearch** [comment]
> @muffinresearch I understand you can help with review and merge. Thanks.

Was the plan to take care of [Rob's comment](https://github.com/mozilla/extension-workshop/pull/1145#pullrequestreview-801557866) re: outdated content separately to this patch?

**Review by Rob--W — APPROVED** [review]
> @muffinresearch I understand you can help with review and merge. Thanks.

@rebloor Was the plan to take care of [Rob's comment](https://github.com/mozilla/extension-workshop/pull/1145#pullrequestreview-801557866) re: outdated content separately to this patch? 

It's part of the update, and lgtm. Upon merging everything is squashed anyway.

**Comment by muffinresearch** [comment]
> > > @muffinresearch I understand you can help with review and merge. Thanks.
> > 
> > 
> > @rebloor Was the plan to take care of [Rob's comment](https://github.com/mozilla/extension-workshop/pull/1145#pullrequestreview-801557866) re: outdated content separately to this patch?
> 
> It's part of the update, and lgtm. Upon merging everything is squashed anyway.

I don't see the XUL related lines covered by the diff. https://github.com/mozilla/extension-workshop/blob/9fef088062d0725a4a25b205fe54786652c09849/src/content/documentation/manage/updating-your-extension.md?plain=1#L96-L101

**Comment by muffinresearch** [comment]
PR to fix nits unrelated to this patch is here: https://github.com/mozilla/extension-workshop/pull/1148

**Comment by rebloor** [comment]
Thanks @muffinresearch

**Pull request merged**
