### PR TITLE
Minor formatting tweak to CLI headings

### PR DESCRIPTION
**Pull request by Zearin**

### CODE REVIEW

**Comment by muffinresearch** [comment]
Before:

web-ext_command_reference___Firefox_Extension_Workshop


After:

**Comment by muffinresearch** [comment]
I think based on trying this, whilst I like the formatting it would be handy to introduce some style tweaks to remove style treatment for `<code>` inside of headings.

**Comment by Zearin** [comment]
Ah, yeah.  I didn’t anticipate how much the dark background would seem imposing in the headings.

I still like monospace fonts for any `command-name` or `--cli-options`, though.  Perhaps with a light grey background instead?

What do you think?

**Comment by muffinresearch** [comment]
> Ah, yeah. I didn’t anticipate how much the dark background would seem imposing in the headings.
> 
> I still like monospace fonts for any `command-name` or `--cli-options`, though. Perhaps with a light grey background instead?
> 
> What do you think?

Yep, leaving the monospace font and just removing the background and font colour (so it's visible) would probably work well.

**Comment by muffinresearch** [comment]
With https://github.com/mozilla/extension-workshop/issues/745 landed, this looks good to go and doesn't need any additional changes.

**Review by muffinresearch — APPROVED** [review]
r+

**Pull request merged**
