### PR TITLE
Fix for pre tag overflow bug in flexbox containers

### LINKED ISSUE #217: Code does not wrap and breaks sidenav
### Describe the problem and steps to reproduce it:

When attempting to display a large amount of code in one line, the text does not wrap.

Example: the bad code example located at https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Source_Code_Submission#Use_of_obfuscated_code 

### What happened?

Code example stretched along the page and subsequently broke the sidenav. 

### What did you expect to happen?

Code example to display in a box wrapped and navigation to still work. 

### Anything else we should know?

image

### PR DESCRIPTION
**Pull request by lancecummings**
Fixes #217

@muffinresearch - fix for overflow bug on code blocks

### CODE REVIEW

**Comment by muffinresearch** [comment]
@lancecummings is there an example already committed that can be looked at to see this in action?

**Comment by lancecummings** [comment]
> @lancecummings is there an example already committed that can be looked at to see this in action?

Yes - go to /documentation/develop/getting-started-with-web-ext/ and scale the browser window narrower, using the Firefox browser.

**Comment by muffinresearch** [comment]
> > @lancecummings is there an example already committed that can be looked at to see this in action?
> 
> Yes - go to /documentation/develop/getting-started-with-web-ext/ and scale the browser window narrower, using the Firefox browser.

Thanks, this patch works well.

**Comment by muffinresearch** [comment]
@lancecummings you'll need to rebase this and then I can merge it.

**Comment by lancecummings** [comment]
> @lancecummings you'll need to rebase this and then I can merge it.

Done!

**Pull request merged**
