### PR TITLE
Update links on landing page

### LINKED ISSUE #284: Update links on landing page
In the section "Ready to build an extension for Firefox" on the landing page, links to the documentation topics need to be changed. 

Screen Shot 2019-08-08 at 9 19 57 AM

Learn --> link to Extension Basics (/extension-basics/) 
Develop --> link to Develop Overview (/documentation/develop/)
Test & Debug --> link to /documentation/develop/temporary-installation-in-firefox/
Publish --> link to Publish Overview (/documentation/publish/)
Manage --> link to Manage Overview (/documentation/manage/

### PR DESCRIPTION
**Pull request by megha-kumarii**
Fixes #284

### CODE REVIEW

**Comment by caitmuenster** [comment]
Thank you @megha-kumarii! 😻 We just need to fix the one test failure and then this can be merged. 

@muffinresearch, I looked at the error but wasn't sure how to fix it. Could you advise? Here's the failure: 

Screen Shot 2019-08-19 at 8 06 28 AM

**Comment by muffinresearch** [comment]
> Thank you @megha-kumarii! 😻 We just need to fix the one test failure and then this can be merged.
> 
> @muffinresearch, I looked at the error but wasn't sure how to fix it. Could you advise? Here's the failure:
> 
> Screen Shot 2019-08-19 at 8 06 28 AM

Looks like the build is starting to take too long for circle-ci, which isn't great. I've restarted it, let's see if that fixes it.

I noticed a build from scratch was taking a really long time locally too. This might require some changes if it continues to head in that direction.

**Comment by muffinresearch** [comment]
Looks good, the build was just spuriously failing.

**Comment by caitmuenster** [comment]
Thanks, @muffinresearch! Does it look like it's going to be complicated to get the local builds from scratch to take less time? Should we file a new issue?

**Comment by muffinresearch** [comment]
> Thanks, @muffinresearch! Does it look like it's going to be complicated to get the local builds from scratch to take less time? Should we file a new issue?

The local builds are only slow when starting from scratch. After you've done it once thereafter a cache is used which speeds it up.

However, I suspect that some of the includes are being used heavily across the entire site and the build is probably executing that code over and over again. To fix that we should investigate profiling the build and see if anything sticks out as being particularly slow or accessed a lot of times.

**Pull request merged**
