### PR TITLE
Update links in pages.yaml

### PR DESCRIPTION
**Pull request by dr0id007**
Changes : -
-URL of the title: "find or create a bug"  
   From:-  "https://www.firefox.com"  
   To:-       " https://bugzilla.mozilla.org"

-URL of the title: "Needs documentation"  
   From:-  "https://www.firefox.com"  
   To:-       " https://mzl.la/33lVHov"

### CODE REVIEW

**Comment by dr0id007** [comment]
Done @caitmuenster

**Comment by dr0id007** [comment]
Thanks for helping.! @caitmuenster .! First commit in foss.!😀

**Comment by caitmuenster** [comment]
Apologies for the delayed response , @dr0id007 -- I just wanted to let you know that your contribution has been added to our [recognition wiki](https://wiki.mozilla.org/Add-ons/Contribute/Recognition). Congratulations on landing your first FOSS patch! 🎉

Would you be interested in creating an account on mozillians.org? I'd be happy to vouch for you!

**Comment by dr0id007** [comment]
Thanks, @caitmuenster 
mozillians.org account:- https://mozillians.org/en-US/u/dr0id007/

**Comment by caitmuenster** [comment]
Yay! You're vouched, @dr0id007. ✨ Welcome onboard -- I look forward to seeing you around!

**Pull request merged**
