### PR TITLE
Edits to content guidelines 

### PR DESCRIPTION
**Pull request by andrewtruongmoz**
@caitmuenster

### CODE REVIEW

**Comment by muffinresearch** [comment]
> This looks good, but I'm not sure why the Circle CI build is failing.
> 
> @muffinresearch, could you take a quick look?

Prettier needs to be run after making edits to the markdown. This ensures a consistent format. You can do this by running `yarn prettier`, but this requires node + yarn and friends to be installed. I'll see about adding something to do this as a follow-up commit so that we don't need to rely on people to run a command just to do some edits to markdown.

**Comment by MeridelW** [comment]
@muffinresearch Can you please share screenshots of the latest pages so I can do final quality check? Thank you!

**Comment by muffinresearch** [comment]
@caitmuenster if the tests are failing those need to be fixed before branches land. Otherwise as is the changes won't be deployed. 

Mainly we seem to have issues with running prettier, so I'd like to understand if anyone is editing the content can run the command prior to committing and if not we probably need to re-think what we're doing there.

**Comment by muffinresearch** [comment]
I've manually fixed prettier in https://github.com/mozilla/extension-workshop/commit/52006515f8eb904cc1182cb8dee6980ba2832e05 so this can be deployed.

**Pull request merged**
